/**
 * Generates the standalone Filedrop embed widget from the theme app extension
 * (upload-widget.liquid) so old themes without app-block support can embed the
 * widget with a small snippet + one <script src>. The liquid stays the single
 * source of truth — re-run whenever the liquid changes:  node scripts/build-embed.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LIQUID = path.join(ROOT, 'extensions/theme-extension/blocks/upload-widget.liquid');
const OUT = path.join(ROOT, 'backend/src/embed/filedrop-embed.generated.ts');

const src = fs.readFileSync(LIQUID, 'utf8');

function between(text, startTag, endTag) {
  const s = text.indexOf(startTag);
  const e = text.indexOf(endTag, s + startTag.length);
  if (s === -1 || e === -1) throw new Error(`Could not find ${startTag}...${endTag}`);
  return text.slice(s + startTag.length, e);
}

// 1) CSS — neutralise the 2 Liquid defaults (JS overrides the colour at runtime).
let css = between(src, '<style>', '</style>')
  .replace(/\{\{\s*block\.settings\.button_color[^}]*\}\}/g, '#008060')
  .replace(/\{\{\s*block\.settings\.border_radius[^}]*\}\}/g, '4');

// 2) Modal HTML — from the first modal div up to <style>. No Liquid in here.
const modalStart = src.indexOf('<div id="cfup-editor-modal"');
const styleStart = src.indexOf('<style>');
if (modalStart === -1 || styleStart === -1 || modalStart > styleStart) throw new Error('Modal extraction failed');
const modals = src.slice(modalStart, styleStart).trim();
if (!modals.includes('cfup-editor-modal') || !modals.includes('cfup-designer-modal')) throw new Error('Modal extraction incomplete');
if (/\{\{|\{%/.test(modals)) throw new Error('Unexpected Liquid in modals');

// 3) The widget script (already reads config from data attributes).
const script = between(src, '<script>', '</script>');
if (/\{\{|\{%/.test(script)) throw new Error('Unexpected Liquid in script');

const cssStr = JSON.stringify(css);
const modalsStr = JSON.stringify(modals);

const embedJs =
`(function(){
  try {
    if (!document.getElementById('cfup-embed-styles')) {
      var st = document.createElement('style');
      st.id = 'cfup-embed-styles';
      st.textContent = ${cssStr};
      document.head.appendChild(st);
    }
    var w = document.getElementById('cfup-upload-widget');
    if (w) {
      if (!w.dataset.apiUrl) {
        var self = document.currentScript || document.querySelector('script[src*="/embed/widget.js"]');
        if (self && self.src) { w.dataset.apiUrl = self.src.replace(/\\/embed\\/widget\\.js.*$/, ''); }
      }
      if (!document.getElementById('cfup-fields-container')) {
        var fc = document.createElement('div'); fc.id = 'cfup-fields-container'; w.appendChild(fc);
      }
      if (!document.getElementById('cfup-editor-modal')) {
        var tpl = document.createElement('template'); tpl.innerHTML = ${modalsStr};
        document.body.appendChild(tpl.content);
      }
    }
  } catch (e) { console.error('[Filedrop embed] setup failed', e); }
})();
${script}`;

const b64 = Buffer.from(embedJs, 'utf8').toString('base64');
const ts =
`/* AUTO-GENERATED by scripts/build-embed.js from upload-widget.liquid. Do not edit by hand. */
export const FILEDROP_EMBED_JS_B64 =
  '${b64}';
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, ts);
console.log('Wrote', path.relative(ROOT, OUT), '(', embedJs.length, 'chars )');
